language: rust

env:
  global:
    - secure: l6L4c/XxVQOjmKTXWs9TjbiRNb9p8jspQvJV3pq91R9ebZxz8CUe2+0JAIDzVaVzSIxsiFFpesZ+/X2yZk9knr0pnZgibqZxy5JzvFUyUaugksIUfB8VB2tHSHipbsIJYxBA8K+knPvY/jH6Wv6EA0FbRHmkaFa1Mas6FRVGjnI=1

script:
    - cargo build
    - cargo test
    - cargo doc

after_script:
    - cd target
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
