[package]
name = "id3"
version = "0.1.3"
authors = ["James Hurst <jh.jameshurst@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/jameshurst/rust-id3"
repository = "https://github.com/jameshurst/rust-id3"
documentation = "https://jameshurst.github.io/rust-id3"
description = "A library for reading and writing ID3 metadata."

[dependencies]
log = "*"
rand = "*"
byteorder = "*"
lazy_static = "*"
num = "*"
flate2 = "*"
encoding = "*"
libc = "*"
