[package]
name = "id3"
version = "0.2.0"
authors = ["James Hurst <jh.jameshurst@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jameshurst/rust-id3"
documentation = "https://jameshurst.github.io/rust-id3"
description = "A library for reading and writing ID3 metadata"
keywords = ["id3", "audio", "parser", "metadata"]
include = ["src/*", "Cargo.toml", "LICENSE", "README.md"]

[features]
unstable = []

[dependencies]
bitflags = "~0.9.0"
byteorder = "~1.0.0"
derive_builder = { version = "~0.4.7", features = [ "private_fields" ] }
encoding = "~0.2.33"
flate2 = "~0.2.19"
lazy_static = "~0.2.8"
regex = "~0.2.1"

[dev-dependencies]
tempdir = "~0.3.4"
