[package]
name = "id3"
version = "0.1.12"
authors = ["James Hurst <jh.jameshurst@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jameshurst/rust-id3"
documentation = "https://jameshurst.github.io/rust-id3"
description = "A library for reading and writing ID3 metadata"
keywords = ["id3", "audio", "parser", "metadata"]
include = ["src/*", "Cargo.toml", "LICENSE", "README.md"]

[dependencies]
log = "~0.3.7"
rand = "~0.3.15"
byteorder = "~1.0.0"
lazy_static = "~0.2.8"
flate2 = "~0.2.19"
encoding = "~0.2.33"
regex = "~0.2.1"
