[package]
name = "id3"
version = "0.1.2"
authors = ["James Hurst <jamesrhurst@outlook.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/jamesrhurst/rust-id3"
repository = "https://github.com/jamesrhurst/rust-id3"
documentation = "https://jamesrhurst.github.io/rust-id3"
description = "A library for reading and writing ID3 metadata."

[dependencies]
log = "*"
rand = "*"
byteorder = "*"
lazy_static = "*"
num = "*"
flate2 = "*"
encoding = "*"
libc = "*"
